### ISSUE TITLE
proxysql hanging 

### ISSUE THREAD

**Issue by arshidkv12** [guriandoro/docker#10]
`sudo docker-compose up proxysql` It is hanging.

**Comment by guriandoro** [comment]
Hi @arshidkv12!

Thanks for trying out the tool. I still have to update the readme on ProxySQL usage, but it is intended to be used once the PXC cluster is up, and the etcd node is up, too. I have created a script that manages this, you can call it like:

```
./make_docker_3-node-pxc.sh up
```

Try it out and let me know if it works!


Thanks

**Comment by guriandoro** [comment]
Closing due to lack of feedback. Feel free to comment back on it, or to open a new one.
